#version 430 core

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba32f) readonly  uniform image2D ht_texture;
layout (binding = 1, rgba32f) writeonly uniform image2D displacement_texture;

uniform int FFT_dimension = 256;
void main (void){
	ivec2 loc = ivec2(gl_GlobalInvocationID.xy);
	int sign = (loc.x + loc.y) %2 ==0? 1: -1;
	float h = imageLoad(ht_texture, loc).r * sign /(FFT_dimension*FFT_dimension);

	imageStore(displacement_texture,  loc, vec4(h,h,h,1.0));
}