#version 430 core


layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0, rgba32f) writeonly uniform image2D tilde_h0k;
layout (binding = 1, rgba32f) writeonly uniform image2D tilde_minus_h0k;


void main(void)
{

	vec4 test_color = vec4(0.0,1.0,0.0,1.0);	
	vec4 test_color_2 = vec4(0.0,0.0,1.0,1.0);	
	imageStore(tilde_h0k, ivec2(gl_GlobalInvocationID.xy), test_color);
	imageStore(tilde_minus_h0k, ivec2(gl_GlobalInvocationID.xy), test_color_2);

}
