#version 430 core
#define M_PI 3.1415926535897932384626433832795

layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0, rgba32f) readonly uniform image2D h0k;

layout (binding = 1, rgba32f) readonly uniform image2D h0minusk;

layout (binding = 2, rgba32f) writeonly uniform image2D hkt;


uniform float time_ms;

void main(void)
{
	float time_s = time_ms/1000.0;
	imageStore(hkt, ivec2(gl_GlobalInvocationID.xy), vec4(sin(time_s)));
}



