#version 430 core

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba32f) readonly   uniform image2D displacement_map;
layout (binding = 1, rgba32f) writeonly  uniform image2D normal_map;

uniform int FFT_dimension ;
uniform float choppy_factor ;
uniform int choppy_on ;     // 1 on, 0 off


void main (void){
	ivec2 loc = ivec2(gl_GlobalInvocationID.xy);
	imageStore(normal_map, loc, vec4(vec3(1.0), 1.0));
}