#version 430 core
#define M_PI 3.1415926535897932384626433832795
#define G 9.81

// log2(N) , FFT/ 16 groups
layout (local_size_x = 1, local_size_y = 16) in;

layout (binding = 0, rgba32f) writeonly uniform image2D twiddle_factor_texture;

uniform int FFT_dimension = 256;   
uniform int ocean_dimension = 256; 



void main(void)
{
	// compute stage

	// compute wk , store wk in rg channel

	//
	imageStore(twiddle_factor_texture, ivec2(gl_GlobalInvocationID.xy), vec4(1.0));
}

